### ISSUE TITLE
Setup.py falhando no Python 3

### ISSUE THREAD

**Issue by ekevoo** [allisson/django-pagseguro2#16]
Estou tentando atualizar e dá esse erro:

    Collecting django-pagseguro2
      Using cached django-pagseguro2-1.0.11.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/private/tmp/pip-build-xxllx4a5/django-pagseguro2/setup.py", line 24, in <module>
            long_description=open('docs/index.rst').read(),
          File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
            return codecs.ascii_decode(input, self.errors)[0]
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 237: ordinal not in range(128)
        ----------------------------------------

    Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-xxllx4a5/django-pagseguro2

**Comment by ekevoo** [comment]
Fui dar uma olhada em um segundo pacote que estava apresentando o mesmo erro e encontrei isso:

https://github.com/gabrielfalcao/HTTPretty/issues/243

Lá algumas soluções são citadas (confesso que não entendi direito). De qualquer forma uma instalação não pode ter resultados diferentes dependendo do locale atual.

**Comment by allisson** [comment]
Eu não consigo reproduzir esse erro na minha máquina, porém eu seto o "export LC_ALL=en_US.UTF-8" no meu .profile.

De qualquer forma, eu troquei o "open('docs/index.rst').read()" por "io.open('docs/index.rst', 'rt', encoding='UTF-8').read()" para tentar evitar esse problema.

Gostaria que você fizesse o teste ai na sua máquina com o: pip install 'https://github.com/allisson/django-pagseguro2/archive/master.zip' e me desse um retorno se o erro ainda persiste.

**Comment by allisson** [comment]
Eu consegui reproduzir esse erro agora:

``` bash
(django-pagseguro2)vagrant@vagrant-ubuntu-trusty-64:/vagrant/django-pagseguro2$ export LC_ALL=C
(django-pagseguro2)vagrant@vagrant-ubuntu-trusty-64:/vagrant/django-pagseguro2$ pip install 'https://github.com/allisson/django-pagseguro2/archive/1.0.11.zip'
Downloading/unpacking https://github.com/allisson/django-pagseguro2/archive/1.0.11.zip
  Downloading 1.0.11.zip
  Running setup.py (path:/tmp/pip-hcolhdw3-build/setup.py) egg_info for package from https://github.com/allisson/django-pagseguro2/archive/1.0.11.zip
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-hcolhdw3-build/setup.py", line 24, in <module>
        long_description=open('docs/index.rst').read(),
      File "/home/vagrant/.virtualenvs/django-pagseguro2/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 237: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-hcolhdw3-build/setup.py", line 24, in <module>

    long_description=open('docs/index.rst').read(),

  File "/home/vagrant/.virtualenvs/django-pagseguro2/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 237: ordinal not in range(128)
```

Já usando a versão que está no master

``` bash
(django-pagseguro2)vagrant@vagrant-ubuntu-trusty-64:/vagrant/django-pagseguro2$ export LC_ALL=C
(django-pagseguro2)vagrant@vagrant-ubuntu-trusty-64:/vagrant/django-pagseguro2$ pip install 'https://github.com/allisson/django-pagseguro2/archive/master.zip' 
Downloading/unpacking https://github.com/allisson/django-pagseguro2/archive/master.zip
  Downloading master.zip
  Running setup.py (path:/tmp/pip-vdgqufus-build/setup.py) egg_info for package from https://github.com/allisson/django-pagseguro2/archive/master.zip
    
    warning: no files found matching 'README.md'
  Requirement already satisfied (use --upgrade to upgrade): django-pagseguro2==1.0.12-dev from https://github.com/allisson/django-pagseguro2/archive/master.zip in /home/vagrant/.virtualenvs/django-pagseguro2/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): Django>=1.4 in /home/vagrant/.virtualenvs/django-pagseguro2/lib/python3.4/site-packages (from django-pagseguro2==1.0.12-dev)
Requirement already satisfied (use --upgrade to upgrade): six in /home/vagrant/.virtualenvs/django-pagseguro2/lib/python3.4/site-packages (from django-pagseguro2==1.0.12-dev)
Requirement already satisfied (use --upgrade to upgrade): requests in /home/vagrant/.virtualenvs/django-pagseguro2/lib/python3.4/site-packages (from django-pagseguro2==1.0.12-dev)
Requirement already satisfied (use --upgrade to upgrade): httpretty<0.8.7 in /home/vagrant/.virtualenvs/django-pagseguro2/lib/python3.4/site-packages (from django-pagseguro2==1.0.12-dev)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /home/vagrant/.virtualenvs/django-pagseguro2/lib/python3.4/site-packages (from django-pagseguro2==1.0.12-dev)
Requirement already satisfied (use --upgrade to upgrade): xmltodict in /home/vagrant/.virtualenvs/django-pagseguro2/lib/python3.4/site-packages (from django-pagseguro2==1.0.12-dev)
Cleaning up...
```

Acredito que o problema está resolvido, mas vou esperar por seu feedback para lançar a versão 1.0.12 :)

**Comment by allisson** [comment]
Resolvido na versão 1.0.12.

**Comment by ekevoo** [comment]
Successfully installed django-pagseguro2-1.0.12

Obrigado!

**Comment by allisson** [comment]
Eu que agradeço, um abraço. :+1:
